name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: "/usr/share/zoneinfo/Europe/Berlin"

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup languages and tools
        uses: gebruederheitz/actions/cached-asdf@1
        with:
          setup-task: true

      - name: Composer Cache
        uses: gebruederheitz/actions/composer-cache@1

      - name: Run the test suite
        run: task ci:test

  lint:
    runs-on: ubuntu-latest
    env:
      TZ: "/usr/share/zoneinfo/Europe/Berlin"

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup languages and tools
        uses: ./.github/actions/cached-asdf

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v6
        with:
          path: vendor
          key: composer-cache-${{ github.ref_name }}-v1-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-cache-${{ github.ref_name }}-v1-

      - name: Cache Composer local
        uses: actions/cache@v6
        with:
          path: ~/.cache/composer
          key: composer-local-cache-${{ github.ref_name }}-v1
          restore-keys: |
            composer-local-cache-${{ github.ref_name }}-

      - name: Run the linting suite
        run: task lint
